import { NextResponse } from "next/server";
import { z } from "zod";
import { getEntitlement } from "@/lib/entitlement";
import { consumeOperation, peekUsage } from "@/lib/usage/server";
import { getToolIds } from "@/lib/tools/registry";
import { getSettings } from "@/lib/settings";
import { tierPriceXaf } from "@/lib/payments/tiers";
import { signInGate } from "@/lib/auth/access";
import { isSupabaseConfigured } from "@/lib/supabase/config";

// This route must never be cached: the answer depends on who is asking and
// how many operations they have already used today.
export const dynamic = "force-dynamic";

const Body = z.object({
  // A UUID generated by the browser. Validated as a shape, not trusted as an
  // identity — it only ever indexes a counter.
  deviceId: z.string().regex(/^[a-z0-9-]{16,64}$/i),
  // Constrained to tools we actually publish, so this cannot be used to write
  // arbitrary strings into the database.
  tool: z.string().refine((value) => getToolIds().includes(value), {
    message: "unknown tool",
  }),
});

/**
 * Ask permission to run one operation, and count it.
 *
 * The browser calls this before processing starts. The decision is made here,
 * from the session cookie and the database — never from anything the page
 * claims about itself.
 */
export async function POST(request: Request) {
  let payload: unknown;
  try {
    payload = await request.json();
  } catch {
    return NextResponse.json({ error: "invalid_body" }, { status: 400 });
  }

  const parsed = Body.safeParse(payload);
  if (!parsed.success) {
    return NextResponse.json({ error: "invalid_body" }, { status: 400 });
  }

  const { tier, isPro, userId } = await getEntitlement();

  // Tools require an account. Refused here, before anything is counted, so a
  // signed-out visitor cannot run an operation by calling this endpoint
  // directly. 401 is the honest status: "who are you?", not "you have run out".
  if (signInGate(isSupabaseConfigured(), userId) === "sign_in_required") {
    return NextResponse.json({ error: "sign_in_required" }, { status: 401 });
  }

  const verdict = await consumeOperation({
    deviceId: parsed.data.deviceId,
    tool: parsed.data.tool,
    headers: request.headers,
    tier,
  });

  return NextResponse.json(
    {
      allowed: verdict.allowed,
      used: verdict.used,
      remaining: verdict.remaining,
      reason: verdict.reason,
      isPro,
      tier,
    },
    // 402 is the honest status for "you have used your free allowance".
    { status: verdict.allowed ? 200 : 402 },
  );
}

/** Today's usage, without consuming anything — used to show "2 left today". */
export async function GET(request: Request) {
  const deviceId = new URL(request.url).searchParams.get("deviceId") ?? "";
  if (!/^[a-z0-9-]{16,64}$/i.test(deviceId)) {
    return NextResponse.json({ error: "invalid_device" }, { status: 400 });
  }

  const { tier, isPro, isAdmin } = await getEntitlement();
  const verdict = await peekUsage(deviceId, tier);
  const settings = await getSettings();

  return NextResponse.json({
    used: verdict.used,
    remaining: verdict.remaining,
    reason: verdict.reason,
    isPro,
    tier,
    // So the account menu can offer the way in to /admin. It is only a
    // signpost: the page itself still returns notFound() to anybody the
    // server does not recognise as an administrator.
    isAdmin,
    // The monthly price of each paid plan, so the paywall inside a tool
    // quotes what the checkout would actually charge rather than a number
    // baked into the page at build time. Public information — it is on the
    // pricing page — so nothing is revealed by sending it here.
    prices: {
      pro: tierPriceXaf(settings.price_xaf, "pro"),
      max: tierPriceXaf(settings.price_xaf, "max"),
    },
  });
}
