import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";
import { requireAdminClient } from "@/lib/supabase/admin";
import { TERM_DAYS, nextEndDate } from "./term";

export { TERM_DAYS, nextEndDate };

/**
 * Granting Pro access.
 *
 * This is the only place in the codebase that turns money into entitlement, and
 * it is deliberately small. Everything that can go wrong with payments goes
 * wrong here: a provider delivering the same notification three times, a user
 * refreshing a success page, two webhooks racing, a "payment" that was never
 * actually paid.
 *
 * Two rules hold throughout:
 *
 *   1. Nothing the browser says is an input. A grant needs a transaction that
 *      this server confirmed with the provider, or an admin acting deliberately.
 *   2. Applying the same transaction twice must grant one month, not two. The
 *      database enforces that with a unique index on (provider, transaction_id);
 *      this module treats the resulting constraint violation as "already done"
 *      rather than as an error.
 */

export type Provider = "notchpay" | "stripe" | "manual";

/** Postgres unique-violation. The whole idempotency guarantee rests on it. */
const UNIQUE_VIOLATION = "23505";

export type GrantInput = {
  userId: string;
  provider: Provider;
  /** The provider's own id for this transaction. Never generated by us for real payments. */
  transactionId: string;
  /** Minor units. XAF has none, so 2000 FCFA is 2000. */
  amount: number;
  currency: string;
  /** Whatever the provider sent, kept for reconciliation and disputes. */
  raw?: unknown;
  /** How many days of access this payment buys. */
  days?: number;
};

export type GrantResult = {
  granted: boolean;
  /** True when this exact transaction had already been applied. */
  duplicate: boolean;
  proUntil: string | null;
};

/**
 * Record a payment and grant the access it bought.
 *
 * Order matters. The payment row is written FIRST, because that insert is what
 * makes the operation idempotent: if it is rejected as a duplicate we stop
 * immediately and no subscription is touched. Granting first and recording
 * afterwards would hand out a free month every time a provider retried.
 */
export async function grantPro(input: GrantInput): Promise<GrantResult> {
  const client = requireAdminClient();
  const days = input.days ?? TERM_DAYS;

  const payment = await client
    .from("payments")
    .insert({
      user_id: input.userId,
      provider: input.provider,
      amount: input.amount,
      currency: input.currency,
      transaction_id: input.transactionId,
      status: "succeeded",
      raw: input.raw ?? null,
    })
    .select("id")
    .single();

  if (payment.error) {
    if (payment.error.code === UNIQUE_VIOLATION) {
      // The provider re-delivered a webhook, or the user refreshed the return
      // page. Both are normal. Report what they already have.
      return { granted: false, duplicate: true, proUntil: await currentProUntil(client, input.userId) };
    }
    throw new Error(`could not record the payment: ${payment.error.message}`);
  }

  const existing = await client
    .from("subscriptions")
    .select("id, end_date")
    .eq("user_id", input.userId)
    .eq("status", "active")
    .order("end_date", { ascending: false })
    .limit(1)
    .maybeSingle();

  const row = existing.data as { id: string; end_date: string | null } | null;
  const end = nextEndDate(row?.end_date ?? null, days);
  const nowIso = new Date().toISOString();

  let subscriptionId: string;

  if (row) {
    const { error } = await client
      .from("subscriptions")
      .update({ end_date: end.toISOString(), provider: input.provider, updated_at: nowIso })
      .eq("id", row.id);
    if (error) throw new Error(`could not extend the subscription: ${error.message}`);
    subscriptionId = row.id;
  } else {
    const created = await client
      .from("subscriptions")
      .insert({
        user_id: input.userId,
        provider: input.provider,
        status: "active",
        start_date: nowIso,
        end_date: end.toISOString(),
        provider_ref: input.transactionId,
      })
      .select("id")
      .single();
    if (created.error) throw new Error(`could not create the subscription: ${created.error.message}`);
    subscriptionId = (created.data as { id: string }).id;
  }

  // Link the payment to what it bought, so the admin view can answer "what did
  // this person actually pay for".
  await client
    .from("payments")
    .update({ subscription_id: subscriptionId })
    .eq("id", (payment.data as { id: string }).id);

  return { granted: true, duplicate: false, proUntil: end.toISOString() };
}

async function currentProUntil(client: SupabaseClient, userId: string): Promise<string | null> {
  const { data } = await client
    .from("subscriptions")
    .select("end_date")
    .eq("user_id", userId)
    .eq("status", "active")
    .order("end_date", { ascending: false })
    .limit(1)
    .maybeSingle();
  return (data as { end_date: string | null } | null)?.end_date ?? null;
}

/** Find a user by the email they signed up with. Admin paths only. */
export async function findUserIdByEmail(email: string): Promise<string | null> {
  const client = requireAdminClient();
  const { data } = await client
    .from("profiles")
    .select("id")
    .ilike("email", email.trim())
    .maybeSingle();
  return (data as { id: string } | null)?.id ?? null;
}
