import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";
import { requireAdminClient } from "@/lib/supabase/admin";
import { TERM_DAYS, nextEndDate } from "./term";

export { TERM_DAYS, nextEndDate };

/**
 * Granting Pro access.
 *
 * This is the only place in the codebase that turns money into entitlement, and
 * it is deliberately small. Everything that can go wrong with payments goes
 * wrong here: a provider delivering the same notification three times, a user
 * refreshing a success page, two webhooks racing, a "payment" that was never
 * actually paid.
 *
 * Two rules hold throughout:
 *
 *   1. Nothing the browser says is an input. A grant needs a transaction that
 *      this server confirmed with the provider, or an admin acting deliberately.
 *   2. Applying the same transaction twice must grant one month, not two. The
 *      database enforces that with a unique index on (provider, transaction_id);
 *      this module treats the resulting constraint violation as "already done"
 *      rather than as an error.
 */

export type Provider = "notchpay" | "stripe" | "manual";

/** Postgres unique-violation. The whole idempotency guarantee rests on it. */
const UNIQUE_VIOLATION = "23505";

export type GrantInput = {
  userId: string;
  provider: Provider;
  /** The provider's own id for this transaction. Never generated by us for real payments. */
  transactionId: string;
  /** Minor units. XAF has none, so 2000 FCFA is 2000. */
  amount: number;
  currency: string;
  /** Whatever the provider sent, kept for reconciliation and disputes. */
  raw?: unknown;
  /** How many days of access this payment buys. */
  days?: number;
};

export type GrantResult = {
  granted: boolean;
  /** True when this exact transaction had already been applied. */
  duplicate: boolean;
  proUntil: string | null;
  /** The payment row, so a receipt can be issued for it. */
  paymentId: string | null;
  paidAt: string | null;
  days: number;
};

/**
 * Record a payment and grant the access it bought.
 *
 * Order matters. The payment row is written FIRST, because that insert is what
 * makes the operation idempotent: if it is rejected as a duplicate we stop
 * immediately and no subscription is touched. Granting first and recording
 * afterwards would hand out a free month every time a provider retried.
 */
export async function grantPro(input: GrantInput): Promise<GrantResult> {
  const client = requireAdminClient();
  const days = input.days ?? TERM_DAYS;

  const payment = await client
    .from("payments")
    .insert({
      user_id: input.userId,
      provider: input.provider,
      amount: input.amount,
      currency: input.currency,
      transaction_id: input.transactionId,
      status: "succeeded",
      raw: input.raw ?? null,
    })
    .select("id, created_at")
    .single();

  if (payment.error) {
    if (payment.error.code === UNIQUE_VIOLATION) {
      // The provider re-delivered a webhook, or the admin re-entered a
      // transaction id they were not sure about. Both are normal — and both
      // should still produce the ORIGINAL receipt, so the customer who asks
      // for it a second time gets the same reference, not a new one.
      const existing = await client
        .from("payments")
        .select("id, created_at")
        .eq("provider", input.provider)
        .eq("transaction_id", input.transactionId)
        .maybeSingle();
      const row = existing.data as { id: string; created_at: string } | null;

      return {
        granted: false,
        duplicate: true,
        proUntil: await currentProUntil(client, input.userId),
        paymentId: row?.id ?? null,
        paidAt: row?.created_at ?? null,
        days,
      };
    }
    throw new Error(`could not record the payment: ${payment.error.message}`);
  }

  const created = payment.data as { id: string; created_at: string };

  const existing = await client
    .from("subscriptions")
    .select("id, end_date")
    .eq("user_id", input.userId)
    .eq("status", "active")
    .order("end_date", { ascending: false })
    .limit(1)
    .maybeSingle();

  const row = existing.data as { id: string; end_date: string | null } | null;
  const end = nextEndDate(row?.end_date ?? null, days);
  const nowIso = new Date().toISOString();

  let subscriptionId: string;

  if (row) {
    const { error } = await client
      .from("subscriptions")
      .update({ end_date: end.toISOString(), provider: input.provider, updated_at: nowIso })
      .eq("id", row.id);
    if (error) throw new Error(`could not extend the subscription: ${error.message}`);
    subscriptionId = row.id;
  } else {
    const inserted = await client
      .from("subscriptions")
      .insert({
        user_id: input.userId,
        provider: input.provider,
        status: "active",
        start_date: nowIso,
        end_date: end.toISOString(),
        provider_ref: input.transactionId,
      })
      .select("id")
      .single();
    if (inserted.error) throw new Error(`could not create the subscription: ${inserted.error.message}`);
    subscriptionId = (inserted.data as { id: string }).id;
  }

  // Link the payment to what it bought, so the admin view can answer "what did
  // this person actually pay for".
  await client
    .from("payments")
    .update({ subscription_id: subscriptionId })
    .eq("id", created.id);

  return {
    granted: true,
    duplicate: false,
    proUntil: end.toISOString(),
    paymentId: created.id,
    paidAt: created.created_at,
    days,
  };
}

async function currentProUntil(client: SupabaseClient, userId: string): Promise<string | null> {
  const { data } = await client
    .from("subscriptions")
    .select("end_date")
    .eq("user_id", userId)
    .eq("status", "active")
    .order("end_date", { ascending: false })
    .limit(1)
    .maybeSingle();
  return (data as { end_date: string | null } | null)?.end_date ?? null;
}

/**
 * Reserve a payment before sending the customer to a provider.
 *
 * Written as `pending`, with our own reference as the transaction id. This is
 * what lets a webhook arriving minutes later — from a machine that knows
 * nothing about our session — be matched back to an account without trusting a
 * single byte of the return URL.
 */
export async function createPendingPayment(input: {
  userId: string;
  provider: Provider;
  reference: string;
  amount: number;
  currency: string;
  days: number;
  meta?: Record<string, unknown>;
}): Promise<void> {
  const client = requireAdminClient();

  const { error } = await client.from("payments").insert({
    user_id: input.userId,
    provider: input.provider,
    amount: input.amount,
    currency: input.currency,
    transaction_id: input.reference,
    status: "pending",
    // The plan length has to survive the round trip: the webhook tells us the
    // money arrived, not what it was for.
    raw: { days: input.days, ...(input.meta ?? {}) },
  });

  if (error) throw new Error(`could not reserve the payment: ${error.message}`);
}

export type SettleResult =
  | { outcome: "granted"; userId: string; proUntil: string | null; paymentId: string; paidAt: string; days: number }
  | { outcome: "already_settled" }
  | { outcome: "unknown_reference" };

/**
 * Mark a reserved payment as paid and grant what it bought.
 *
 * The idempotency here is the `eq("status", "pending")` on the update. Two
 * webhooks racing, or a webhook racing the customer's return from the payment
 * page, both try the same conditional update; exactly one of them matches a
 * row and the other gets nothing back and stops. No locks, no transaction, no
 * double month.
 *
 * Callers MUST have confirmed with the provider that the money arrived before
 * calling this. It does not check — it cannot, it does not know which provider
 * it is being called for — so that check belongs at the edge, in the webhook
 * and return handlers, where the provider's answer is available.
 */
export async function settlePayment(input: {
  provider: Provider;
  reference: string;
  amount?: number | null;
  currency?: string | null;
  raw?: unknown;
}): Promise<SettleResult> {
  const client = requireAdminClient();

  const claimed = await client
    .from("payments")
    .update({
      status: "succeeded",
      ...(typeof input.amount === "number" ? { amount: input.amount } : {}),
      ...(input.currency ? { currency: input.currency.toUpperCase() } : {}),
    })
    .eq("provider", input.provider)
    .eq("transaction_id", input.reference)
    .eq("status", "pending")
    .select("id, user_id, created_at, raw")
    .maybeSingle();

  const row = claimed.data as
    | { id: string; user_id: string | null; created_at: string; raw: { days?: number } | null }
    | null;

  if (!row) {
    // Either someone got here first (fine — the customer already has their
    // month) or the reference is not one we issued (not fine, but also not
    // something to act on).
    const existing = await client
      .from("payments")
      .select("id")
      .eq("provider", input.provider)
      .eq("transaction_id", input.reference)
      .maybeSingle();

    return existing.data ? { outcome: "already_settled" } : { outcome: "unknown_reference" };
  }

  if (!row.user_id) return { outcome: "unknown_reference" };

  const days = typeof row.raw?.days === "number" ? row.raw.days : TERM_DAYS;

  const subscription = await client
    .from("subscriptions")
    .select("id, end_date")
    .eq("user_id", row.user_id)
    .eq("status", "active")
    .order("end_date", { ascending: false })
    .limit(1)
    .maybeSingle();

  const current = subscription.data as { id: string; end_date: string | null } | null;
  const end = nextEndDate(current?.end_date ?? null, days);
  const nowIso = new Date().toISOString();

  let subscriptionId: string;

  if (current) {
    await client
      .from("subscriptions")
      .update({ end_date: end.toISOString(), provider: input.provider, updated_at: nowIso })
      .eq("id", current.id);
    subscriptionId = current.id;
  } else {
    const inserted = await client
      .from("subscriptions")
      .insert({
        user_id: row.user_id,
        provider: input.provider,
        status: "active",
        start_date: nowIso,
        end_date: end.toISOString(),
        provider_ref: input.reference,
      })
      .select("id")
      .single();

    if (inserted.error) {
      throw new Error(`could not create the subscription: ${inserted.error.message}`);
    }
    subscriptionId = (inserted.data as { id: string }).id;
  }

  await client
    .from("payments")
    .update({
      subscription_id: subscriptionId,
      raw: { ...(row.raw ?? {}), settled: input.raw ?? null, settledAt: nowIso },
    })
    .eq("id", row.id);

  return {
    outcome: "granted",
    userId: row.user_id,
    proUntil: end.toISOString(),
    paymentId: row.id,
    paidAt: row.created_at,
    days,
  };
}

/** Find a user by the email they signed up with. Admin paths only. */
export async function findUserIdByEmail(email: string): Promise<string | null> {
  const client = requireAdminClient();
  const { data } = await client
    .from("profiles")
    .select("id")
    .ilike("email", email.trim())
    .maybeSingle();
  return (data as { id: string } | null)?.id ?? null;
}
