import "server-only";
import { tierOf, tierRank, type TierId } from "./tiers";

import type { SupabaseClient } from "@supabase/supabase-js";
import { requireAdminClient } from "@/lib/supabase/admin";
import { TERM_DAYS, nextEndDate } from "./term";

export { TERM_DAYS, nextEndDate };

/**
 * Granting Pro access.
 *
 * This is the only place in the codebase that turns money into entitlement, and
 * it is deliberately small. Everything that can go wrong with payments goes
 * wrong here: a provider delivering the same notification three times, a user
 * refreshing a success page, two webhooks racing, a "payment" that was never
 * actually paid.
 *
 * Two rules hold throughout:
 *
 *   1. Nothing the browser says is an input. A grant needs a transaction that
 *      this server confirmed with the provider, or an admin acting deliberately.
 *   2. Applying the same transaction twice must grant one month, not two. The
 *      database enforces that with a unique index on (provider, transaction_id);
 *      this module treats the resulting constraint violation as "already done"
 *      rather than as an error.
 */

export type Provider = "notchpay" | "campay" | "stripe" | "manual";

/** Postgres unique-violation. The whole idempotency guarantee rests on it. */
const UNIQUE_VIOLATION = "23505";

export type GrantInput = {
  userId: string;
  provider: Provider;
  /** The provider's own id for this transaction. Never generated by us for real payments. */
  transactionId: string;
  /** Minor units. XAF has none, so 2000 FCFA is 2000. */
  amount: number;
  currency: string;
  /** Whatever the provider sent, kept for reconciliation and disputes. */
  raw?: unknown;
  /** How many days of access this payment buys. */
  days?: number;
  /** Which plan was bought. Defaults to pro — every sale before Max was Pro. */
  tier?: TierId;
};

export type GrantResult = {
  granted: boolean;
  /** True when this exact transaction had already been applied. */
  duplicate: boolean;
  proUntil: string | null;
  /** The payment row, so a receipt can be issued for it. */
  paymentId: string | null;
  paidAt: string | null;
  days: number;
};

/**
 * The better of two tiers.
 *
 * Used when a payment lands on an existing subscription. An upgrade must raise
 * the tier; a renewal at the same level must not change it; and a cheaper
 * renewal must NOT lower it, because the customer has already paid for the
 * higher one until a date that has not arrived yet.
 */
function bestTier(current: string | null | undefined, incoming: TierId): TierId {
  const a = tierOf(current);
  return tierRank(a) > tierRank(incoming) ? a : incoming;
}

/**
 * Record a payment and grant the access it bought.
 *
 * Order matters. The payment row is written FIRST, because that insert is what
 * makes the operation idempotent: if it is rejected as a duplicate we stop
 * immediately and no subscription is touched. Granting first and recording
 * afterwards would hand out a free month every time a provider retried.
 */
export async function grantPro(input: GrantInput): Promise<GrantResult> {
  const client = requireAdminClient();
  const days = input.days ?? TERM_DAYS;
  const tier: TierId = input.tier ?? "pro";

  const payment = await client
    .from("payments")
    .insert({
      user_id: input.userId,
      provider: input.provider,
      tier,
      amount: input.amount,
      currency: input.currency,
      transaction_id: input.transactionId,
      status: "succeeded",
      raw: input.raw ?? null,
    })
    .select("id, created_at")
    .single();

  if (payment.error) {
    if (payment.error.code === UNIQUE_VIOLATION) {
      // The provider re-delivered a webhook, or the admin re-entered a
      // transaction id they were not sure about. Both are normal — and both
      // should still produce the ORIGINAL receipt, so the customer who asks
      // for it a second time gets the same reference, not a new one.
      const existing = await client
        .from("payments")
        .select("id, created_at")
        .eq("provider", input.provider)
        .eq("transaction_id", input.transactionId)
        .maybeSingle();
      const row = existing.data as { id: string; created_at: string } | null;

      return {
        granted: false,
        duplicate: true,
        proUntil: await currentProUntil(client, input.userId),
        paymentId: row?.id ?? null,
        paidAt: row?.created_at ?? null,
        days,
      };
    }
    throw new Error(`could not record the payment: ${payment.error.message}`);
  }

  const created = payment.data as { id: string; created_at: string };

  const existing = await client
    .from("subscriptions")
    .select("id, end_date, tier")
    .eq("user_id", input.userId)
    .eq("status", "active")
    .order("end_date", { ascending: false })
    .limit(1)
    .maybeSingle();

  const row = existing.data as { id: string; end_date: string | null; tier?: string | null } | null;
  const end = nextEndDate(row?.end_date ?? null, days);
  const nowIso = new Date().toISOString();

  let subscriptionId: string;

  if (row) {
    const { error } = await client
      .from("subscriptions")
      // An upgrade extends the same row and RAISES the tier; a renewal at the
      // same level leaves it alone. Never lower it mid-term: somebody who
      // bought Max and then renews monthly Pro has paid for Max until the date
      // they paid for, and quietly demoting them would be taking it back.
      .update({
        end_date: end.toISOString(),
        provider: input.provider,
        updated_at: nowIso,
        tier: bestTier(row?.tier, tier),
      })
      .eq("id", row.id);
    if (error) throw new Error(`could not extend the subscription: ${error.message}`);
    subscriptionId = row.id;
  } else {
    const inserted = await client
      .from("subscriptions")
      .insert({
        user_id: input.userId,
        provider: input.provider,
        status: "active",
        start_date: nowIso,
        end_date: end.toISOString(),
        provider_ref: input.transactionId,
        tier,
      })
      .select("id")
      .single();
    if (inserted.error) throw new Error(`could not create the subscription: ${inserted.error.message}`);
    subscriptionId = (inserted.data as { id: string }).id;
  }

  // Link the payment to what it bought, so the admin view can answer "what did
  // this person actually pay for".
  await client
    .from("payments")
    .update({ subscription_id: subscriptionId })
    .eq("id", created.id);

  // Only on the branch that actually granted. The duplicate branch above
  // returns before reaching here, which is what stops a provider's third
  // delivery of the same webhook from being a third receipt in somebody's
  // inbox.
  await announceSettlement({
    userId: input.userId,
    paymentId: created.id,
    amount: input.amount,
    currency: input.currency.toUpperCase(),
    paidAt: created.created_at,
    proUntil: end.toISOString(),
    days,
    tier,
  });

  return {
    granted: true,
    duplicate: false,
    proUntil: end.toISOString(),
    paymentId: created.id,
    paidAt: created.created_at,
    days,
  };
}

/**
 * Tell the customer, and let nothing about it reach the caller.
 *
 * Both grant paths call this on the branch that granted, and only there. It
 * catches everything, including the email lookup: this function runs after the
 * money has been confirmed and the subscription written, so there is no failure
 * it can report that would be worth undoing an activation for. A log line is
 * the whole error handling, on purpose.
 *
 * The import is lazy. `grantPro` and `settlePayment` are reached from tests and
 * from scripts that have no mail configuration and no need of one, and a static
 * import would pull the mailer — and its `server-only` guard — into every one
 * of those.
 */
async function announceSettlement(settled: {
  userId: string;
  paymentId: string;
  amount: number;
  currency: string;
  paidAt: string;
  proUntil: string | null;
  days: number;
  tier: TierId;
}): Promise<void> {
  try {
    const { notifyPaymentSettled } = await import("@/lib/email/notify");
    const email = await emailForUserId(settled.userId);
    // A receipt names a paid plan. `TierId` also contains "free", which no
    // payment should ever carry; if one does, that is a data fault, so it is
    // logged rather than passed through. The receipt then reads "Pro", which
    // is what it already says for every payment made before Max existed —
    // not a guess invented here.
    const paidTier = settled.tier === "max" || settled.tier === "pro" ? settled.tier : undefined;
    if (!paidTier) {
      console.warn(`[Tools.cm] payment ${settled.paymentId} settled with tier "${settled.tier}"`);
    }
    const result = await notifyPaymentSettled({ ...settled, tier: paidTier, email });
    if (!result.sent && result.reason !== "no mail provider configured") {
      console.warn(`[Tools.cm] no receipt sent for payment ${settled.paymentId}: ${result.reason}`);
    }
  } catch (error) {
    console.error(
      `[Tools.cm] the receipt for payment ${settled.paymentId} could not be sent:`,
      error instanceof Error ? error.message : error,
    );
  }
}

async function currentProUntil(client: SupabaseClient, userId: string): Promise<string | null> {
  const { data } = await client
    .from("subscriptions")
    .select("end_date")
    .eq("user_id", userId)
    .eq("status", "active")
    .order("end_date", { ascending: false })
    .limit(1)
    .maybeSingle();
  return (data as { end_date: string | null } | null)?.end_date ?? null;
}

/**
 * Reserve a payment before sending the customer to a provider.
 *
 * Written as `pending`, with our own reference as the transaction id. This is
 * what lets a webhook arriving minutes later — from a machine that knows
 * nothing about our session — be matched back to an account without trusting a
 * single byte of the return URL.
 */
export async function createPendingPayment(input: {
  userId: string;
  provider: Provider;
  reference: string;
  amount: number;
  currency: string;
  days: number;
  tier?: TierId;
  meta?: Record<string, unknown>;
}): Promise<void> {
  const client = requireAdminClient();

  const { error } = await client.from("payments").insert({
    user_id: input.userId,
    provider: input.provider,
    tier: input.tier ?? "pro",
    amount: input.amount,
    currency: input.currency,
    transaction_id: input.reference,
    status: "pending",
    // The plan length has to survive the round trip: the webhook tells us the
    // money arrived, not what it was for.
    // The plan length AND the tier have to survive the round trip: the
    // webhook tells us the money arrived, not what it was for.
    raw: { days: input.days, tier: input.tier ?? "pro", ...(input.meta ?? {}) },
  });

  if (error) throw new Error(`could not reserve the payment: ${error.message}`);
}

/**
 * Remember the provider's own identifier for a payment we already reserved.
 *
 * CamPay's status endpoint takes THEIR reference, not ours, and we only learn
 * it after the payment link is created. Without this the return page would
 * have no way to ask whether the customer actually paid.
 */
export async function attachProviderRef(
  provider: Provider,
  reference: string,
  providerRef: string,
): Promise<void> {
  const client = requireAdminClient();

  const existing = await client
    .from("payments")
    .select("raw")
    .eq("provider", provider)
    .eq("transaction_id", reference)
    .maybeSingle();

  const raw = (existing.data as { raw: Record<string, unknown> | null } | null)?.raw ?? {};

  await client
    .from("payments")
    .update({ raw: { ...raw, providerRef } })
    .eq("provider", provider)
    .eq("transaction_id", reference);
}

export type SettleResult =
  | { outcome: "granted"; userId: string; proUntil: string | null; paymentId: string; paidAt: string; days: number }
  | { outcome: "already_settled" }
  | { outcome: "unknown_reference" };

/**
 * Mark a reserved payment as paid and grant what it bought.
 *
 * The idempotency here is the `eq("status", "pending")` on the update. Two
 * webhooks racing, or a webhook racing the customer's return from the payment
 * page, both try the same conditional update; exactly one of them matches a
 * row and the other gets nothing back and stops. No locks, no transaction, no
 * double month.
 *
 * Callers MUST have confirmed with the provider that the money arrived before
 * calling this. It does not check — it cannot, it does not know which provider
 * it is being called for — so that check belongs at the edge, in the webhook
 * and return handlers, where the provider's answer is available.
 */
export async function settlePayment(input: {
  provider: Provider;
  reference: string;
  amount?: number | null;
  currency?: string | null;
  raw?: unknown;
}): Promise<SettleResult> {
  const client = requireAdminClient();

  const claimed = await client
    .from("payments")
    .update({
      status: "succeeded",
      ...(typeof input.amount === "number" ? { amount: input.amount } : {}),
      ...(input.currency ? { currency: input.currency.toUpperCase() } : {}),
    })
    .eq("provider", input.provider)
    .eq("transaction_id", input.reference)
    .eq("status", "pending")
    .select("id, user_id, created_at, amount, currency, raw")
    .maybeSingle();

  const row = claimed.data as
    | {
        id: string;
        user_id: string | null;
        created_at: string;
        amount: number | null;
        currency: string | null;
        raw: { days?: number; tier?: string } | null;
      }
    | null;

  if (!row) {
    // Either someone got here first (fine — the customer already has their
    // month) or the reference is not one we issued (not fine, but also not
    // something to act on).
    const existing = await client
      .from("payments")
      .select("id")
      .eq("provider", input.provider)
      .eq("transaction_id", input.reference)
      .maybeSingle();

    return existing.data ? { outcome: "already_settled" } : { outcome: "unknown_reference" };
  }

  if (!row.user_id) return { outcome: "unknown_reference" };

  const days = typeof row.raw?.days === "number" ? row.raw.days : TERM_DAYS;
  // The tier was recorded when the payment was created; the provider only
  // tells us the money arrived, never what it was for.
  const tier = tierOf(typeof row.raw?.tier === "string" ? row.raw.tier : "pro");

  const subscription = await client
    .from("subscriptions")
    .select("id, end_date, tier")
    .eq("user_id", row.user_id)
    .eq("status", "active")
    .order("end_date", { ascending: false })
    .limit(1)
    .maybeSingle();

  const current = subscription.data as { id: string; end_date: string | null; tier?: string | null } | null;
  const end = nextEndDate(current?.end_date ?? null, days);
  const nowIso = new Date().toISOString();

  let subscriptionId: string;

  if (current) {
    await client
      .from("subscriptions")
      // An upgrade extends the same row and RAISES the tier; a renewal at the
      // same level leaves it alone. Never lower it mid-term: somebody who
      // bought Max and then renews monthly Pro has paid for Max until the date
      // they paid for, and quietly demoting them would be taking it back.
      .update({
        end_date: end.toISOString(),
        provider: input.provider,
        updated_at: nowIso,
        tier: bestTier(current?.tier, tier),
      })
      .eq("id", current.id);
    subscriptionId = current.id;
  } else {
    const inserted = await client
      .from("subscriptions")
      .insert({
        user_id: row.user_id,
        provider: input.provider,
        status: "active",
        tier,
        start_date: nowIso,
        end_date: end.toISOString(),
        provider_ref: input.reference,
      })
      .select("id")
      .single();

    if (inserted.error) {
      throw new Error(`could not create the subscription: ${inserted.error.message}`);
    }
    subscriptionId = (inserted.data as { id: string }).id;
  }

  await client
    .from("payments")
    .update({
      subscription_id: subscriptionId,
      raw: { ...(row.raw ?? {}), settled: input.raw ?? null, settledAt: nowIso },
    })
    .eq("id", row.id);

  // The customer is told, from here, for every provider at once. Each webhook
  // and return handler would otherwise need its own copy of this — and the one
  // that got forgotten would be the one whose customers never hear back.
  //
  // Placed after every write, and awaited. After, because a mail provider must
  // never be able to cost somebody the access they paid for. Awaited, because
  // on Vercel the function stops the moment the response is returned: a promise
  // left dangling here is a receipt that is sometimes sent and sometimes not,
  // depending on how fast the loop happened to get to it.
  await announceSettlement({
    userId: row.user_id,
    paymentId: row.id,
    amount: (typeof input.amount === "number" ? input.amount : row.amount) ?? 0,
    currency: (input.currency ?? row.currency ?? "XAF").toUpperCase(),
    paidAt: row.created_at,
    proUntil: end.toISOString(),
    days,
    tier,
  });

  return {
    outcome: "granted",
    userId: row.user_id,
    proUntil: end.toISOString(),
    paymentId: row.id,
    paidAt: row.created_at,
    days,
  };
}

/**
 * Find a user by the email they signed up with. Admin paths only.
 *
 * Resolved through Supabase Auth, not through `profiles.email`.
 *
 * `profiles.email` is a copy, and a copy the account holder can write: the
 * browser holds `update (email)` on it so people can correct their own address
 * on the account page. That is a fine feature and it stays — but it means the
 * column is a claim, not an identity, and every admin grant resolves its
 * subject here. Resolving against a column the subject controls had two
 * consequences:
 *
 *   **Theft.** A user who set their `profiles.email` to the address of
 *   somebody about to be activated received that grant instead — including
 *   `is_unlimited`, which is owner-level access.
 *
 *   **Denial.** A user who merely copied an existing address made two rows
 *   match, so `maybeSingle()` returned nothing and the legitimate activation
 *   failed as "no such account" — telling the person who actually paid that
 *   they do not exist.
 *
 * `auth.users.email` is written only by Supabase Auth, is verified, and is
 * unique. It is the address the person can actually sign in with, which is
 * also the only address an admin means when they type one.
 *
 * Falls back to the profile copy only when the Auth lookup is unavailable —
 * an older supabase-js, or a key without admin scope — because an admin who
 * cannot grant at all is worse than one who grants against a weaker key. The
 * fallback additionally refuses an ambiguous match, which the original did
 * only by accident.
 */
export async function findUserIdByEmail(email: string): Promise<string | null> {
  const client = requireAdminClient();
  const wanted = email.trim().toLowerCase();
  if (!wanted) return null;

  try {
    // listUsers is paginated; the filter is applied server-side where the
    // version supports it, and re-applied here either way so a server that
    // ignores the filter cannot return the wrong person.
    const { data, error } = await client.auth.admin.listUsers({ page: 1, perPage: 200 });
    if (!error && data?.users) {
      const matches = data.users.filter(
        (user) => (user.email ?? "").trim().toLowerCase() === wanted,
      );
      if (matches.length === 1) return matches[0].id;
      // More than one account can legitimately share an address in Supabase —
      // one per sign-in method. They are the same person, so the oldest wins
      // rather than the grant failing.
      if (matches.length > 1) {
        return matches.sort((a, b) => (a.created_at ?? "").localeCompare(b.created_at ?? ""))[0].id;
      }
      return null;
    }
  } catch {
    // Fall through to the profile copy.
  }

  const { data } = await client.from("profiles").select("id").ilike("email", wanted).limit(2);
  const rows = (data as { id: string }[] | null) ?? [];
  return rows.length === 1 ? rows[0].id : null;
}

/**
 * The address to write to for an account.
 *
 * The mirror of `findUserIdByEmail`, and resolved the same way and for the same
 * reason: through Supabase Auth first. `profiles.email` is a copy the account
 * holder can write, so using it here would let somebody have another person's
 * receipt — including the amount they paid — delivered to an address of their
 * choosing. The Auth address is the one they can actually sign in with.
 *
 * The profile copy is still the fallback, because a receipt that goes nowhere
 * is worse than one sent to a weaker source of the same address, and this is
 * only ever used to notify, never to decide who gets access.
 *
 * Returns null rather than throwing: every caller is a notification path.
 */
export async function emailForUserId(userId: string): Promise<string | null> {
  const client = requireAdminClient();
  if (!userId) return null;

  try {
    const { data, error } = await client.auth.admin.getUserById(userId);
    const address = data?.user?.email?.trim();
    if (!error && address) return address;
  } catch {
    // Fall through to the profile copy.
  }

  try {
    const { data } = await client
      .from("profiles")
      .select("email")
      .eq("id", userId)
      .maybeSingle();
    const address = (data as { email?: string | null } | null)?.email?.trim();
    return address || null;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Payments that did not succeed
// ---------------------------------------------------------------------------

/**
 * Mark a reserved payment as failed, cancelled or expired.
 *
 * `payment_status` has had `failed` and `refunded` since the first migration
 * and nothing ever wrote either of them. The consequence was quiet and it
 * compounded: a customer who opened a checkout page and closed it left a
 * `pending` row that stayed pending for ever. Nothing cleared it, nothing
 * reported it, and the admin figures counted an abandoned click the same way
 * they counted a payment still in flight. After a few hundred visitors, "what
 * is pending right now" — the one question that tells you a provider has gone
 * quiet — stops being answerable.
 *
 * Only a `pending` row is touched, for the same reason settlement only touches
 * a pending row: a payment that already succeeded must never be walked back by
 * a late failure notification, which is exactly the shape of a provider
 * retrying an old event.
 */
export async function markPaymentFailed(input: {
  provider: Provider;
  reference: string;
  reason?: string;
  raw?: unknown;
}): Promise<"marked" | "already_settled" | "unknown_reference"> {
  const client = requireAdminClient();

  const { data, error } = await client
    .from("payments")
    .update({
      status: "failed",
      raw: {
        failedAt: new Date().toISOString(),
        reason: input.reason ?? null,
        detail: input.raw ?? null,
      },
    })
    .eq("provider", input.provider)
    .eq("transaction_id", input.reference)
    .eq("status", "pending")
    .select("id")
    .maybeSingle();

  if (error) {
    console.error("[Tools.cm] could not mark a payment failed:", error.message);
    return "unknown_reference";
  }
  if (data) return "marked";

  // Nothing matched: either the reference is unknown, or the row is no longer
  // pending. Told apart, because they mean different things to a caller — one
  // is a mistake and the other is a race that already resolved the right way.
  const { data: existing } = await client
    .from("payments")
    .select("status")
    .eq("provider", input.provider)
    .eq("transaction_id", input.reference)
    .maybeSingle();
  return existing ? "already_settled" : "unknown_reference";
}

/**
 * Close out payments nobody ever completed.
 *
 * A checkout page opened and abandoned leaves a pending row; after a few hours
 * it is not "in flight", it is abandoned, and leaving it pending makes the
 * only useful reading of that column impossible.
 *
 * Twelve hours by default — long enough that a Mobile Money confirmation held
 * up overnight is not written off, short enough that yesterday's abandoned
 * clicks are out of today's picture. Expiring a payment grants nothing and
 * takes nothing away: it only stops the row claiming to be undecided.
 */
export async function expireStalePayments(olderThanHours = 12): Promise<number> {
  const client = requireAdminClient();
  const cutoff = new Date(Date.now() - Math.max(1, olderThanHours) * 3_600_000).toISOString();

  const { data, error } = await client
    .from("payments")
    .update({ status: "failed", raw: { expiredAt: new Date().toISOString(), reason: "abandoned" } })
    .eq("status", "pending")
    .lt("created_at", cutoff)
    .select("id");

  if (error) {
    console.error("[Tools.cm] could not expire stale payments:", error.message);
    return 0;
  }
  return (data ?? []).length;
}
